version: '3.4'

services:
  web-ecommerce:
      env_file:
      - .env.example
      image: web-ecommerce
      container_name: web-ecommerce
      build:
        dockerfile: Dockerfile
      restart: always
      ports:
        - "443:${HTTPS_PORT}"
        - "80:${PORT}"
      volumes:
        - /opt/web-ecommerce/logs:/logs
      networks:
        - web-ecommerce
      environment:
        - PAYMENT_SERVICE_URL=http://web-payment:8880

networks:
  web-ecommerce:
    driver: bridge

