# This is a basic workflow to help you get started with Actions

- name: Setup Node.js environment
  uses: actions/setup-node@v4.0.0

deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sarah-oo"
          heroku_email: "sarahchimao@gmail.com"